apiVersion: v1
kind: Secret
metadata:
    name: pipeline-hmac-key
    namespace: apps
    annotations:
        config.internal/rotated-by: mallory@example.com
        config.internal/note: webhook HMAC — do not delete until pipeline migration complete
type: Opaque
stringData:
    hmac-key: ENC[AES256_GCM,data:LoACf1VJHgC8x5SBa4XLYWKA+BR8SadZafoE1dNroNBMGSX1SF5iO2Xpdv612rxg4RvKou8VAEncBBc6UHeORc63g9VYsXZOl/FNyQ==,iv:pu6t3eOua/MqdCcHdFEt7S1mr2LfAP3awSc9cB61u3Y=,tag:UBvqRV0as5wxaa8NNUBv+Q==,type:str]
sops:
    age:
        - recipient: age1l2w7hkcmzadyg7z647t33ply3hrnc3nsuuzcrxacqsr8jh629drshdqqqh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXpsNFBKM3dBMzBxdE8v
            R3ZIZ3JvMDdtTzJmdktqZ1AxQ3dYcjJYbGo4CkQ3eHAxRmVTY29ySVBGZ0h2V1VE
            T3JPOXd0cTNmR2lTN1JNUkJYemdHSHcKLS0tIFpyUHFEd3Z4ZUVsMGJVZmRrVFJs
            bHB4OC9VZWlCL2E4SDUxeHY4ZVBrUjgKtGNE6z7DGC6CGqqAhb6dhmXER6nS9tZ8
            iIJVwF/U88XTZykqMwYRpYEijbeth879EQA5PPhNHefkMWqj3rYo7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T10:59:32Z"
    mac: ENC[AES256_GCM,data:LhutvjAnE5YXTllOUqQoSX6cmhfH22Ie+PRzECr8GwaOHvs5iiAFahwXlgDOL46XLPV4ev6dDjoDFMU7OfaWsgXf/71lsZsCeD4OnRg3bpjzR6FKykiC/h/CofY2rp5+GSoDLKPUisyvYdruON339skc7h7umwrCk1vUccg2/3Y=,iv:MalHEfrjj5bOQ4Z4AJYks9cgdVySxquGog5V+1rTAM0=,tag:qXcy4g7t0GJ3pz9auVXYyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
