apiVersion: v1
kind: ServiceAccount
metadata:
  name: hooky-sa
  namespace: apps
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::430354129336:role/eks-hooky-data-reader"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-tester
  namespace: apps
  labels:
    app: webhook-tester
  annotations:
    platform.internal/owner: "mallory@example.com"
    platform.internal/note: "internal webhook tester — for integration testing"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-tester
  template:
    metadata:
      labels:
        app: webhook-tester
    spec:
      serviceAccountName: hooky-sa
      containers:
        - name: hooky
          image: 430354129336.dkr.ecr.eu-west-1.amazonaws.com/ctf/hooky:latest
          args: ["--mode=hooky"]
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: CTF_DEBUG_TOKEN
              value: "WW91IHdlcmUgbmV2ZXIgbWVhbnQgdG8u"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-tester
  namespace: apps
spec:
  selector:
    app: webhook-tester
  ports:
    - port: 8080
      targetPort: 8080
