apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-extractor
  namespace: datagovuk
  labels:
    app: metadata-extractor
  annotations:
    platform.internal/owner: "mallory@example.com"
    platform.internal/note: "extracts metadata from upstream dataset registries"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-extractor
  template:
    metadata:
      labels:
        app: metadata-extractor
    spec:
      containers:
        - name: extractor
          image: 430354129336.dkr.ecr.eu-west-1.amazonaws.com/ctf/metadata-extractor:latest
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-extractor
  namespace: datagovuk
spec:
  selector:
    app: metadata-extractor
  ports:
    - port: 8080
      targetPort: 8080
